.travis.yml, test/ApplicationSpec.scala
Copied scalachess configuration
=> Enable travis build

conf/application.conf
in response to https://hackerone.com/reports/1086745
=> clarify that play.http.secret.key is not secret here

project/build.properties
https://github.com/sbt/sbt/releases/tag/v1.9.5
=> Update sbt 1.9.5

modules/api/src/main/smithy/health.smithy, modules/api/src/main/smithy/search.smithy, modules/e2e/src/test/scala/CompatSuite.scala
As We already have breaking changes
=> Add /api prefix for all endpoints

build.sbt, modules/api/src/main/smithy/_global.smithy, modules/api/src/main/smithy/search.smithy, modules/app/src/main/scala/service.search.scala, modules/client/src/main/scala/NoopSearchClient.scala, modules/client/src/main/scala/PlaySearchClient.scala, modules/e2e/src/test/scala/CompatSuite.scala
=> Inline ouputs for smithy

build.sbt, modules/core/src/main/scala/models.scala, modules/ingestor/src/main/scala/cli.scala, modules/ingestor/src/main/scala/ingestor.forum.scala, modules/ingestor/src/main/scala/ingestor.scala, modules/ingestor/src/main/scala/package.scala, project/Dependencies.scala
```sh
sbt "ingestor/runMain lila.search.ingestor.cli --index forum --since 1710236967 -u 1710236967"
```
or 
```
sbt stage
./modules/ingestor/target/universal/stage/bin/cli index --index forum --since 1710942873 --dry
```
Both need to provide env variables
=> Implement cli application for backfil forum posts

modules/ingestor/src/main/scala/app.config.scala, modules/ingestor/src/main/scala/ingestor.forum.scala
Follow https://github.com/lichess-org/lila/pull/15575
Will need to wait for a lila deploy
close #243
=> Index full forum posts

modules/ingestor/src/main/scala/app.config.scala, modules/ingestor/src/main/scala/ingestor.forum.scala
Follow up https://github.com/lichess-org/lila/pull/15575
=> Filter out posts that have more than 5000 chars

modules/ingestor/src/main/scala/ingestor.forum.scala
This leads to less computation in application level.
=> Filter out over size forum posts in change stream

modules/ingestor/src/main/scala/ingestor.forum.scala, modules/ingestor/src/main/scala/ingestor.team.scala, modules/ingestor/src/main/scala/package.scala
When recieve a list of changes, We distinct them by id and only keep the latest changes.
Close https://github.com/lichess-org/lila-search/issues/255
=> Only index the latest change

bin/deploy, build.sbt
Also remove v3 postfix every where
=> Bump lila-search 3.0.0

modules/ingestor/src/main/scala/ingestor.game.scala
=> Do not index games without real players

modules/ingestor/src/main/scala/ingestor.game.scala
And log the document when it's happen
=> Make p0 and p1 field optional

modules/ingestor/src/main/scala/app.scala, modules/ingestor/src/main/scala/cli.scala, modules/ingestor/src/main/scala/ingestor.forum.scala, modules/ingestor/src/main/scala/ingestor.game.scala, modules/ingestor/src/main/scala/ingestor.scala, modules/ingestor/src/main/scala/ingestor.study.scala, modules/ingestor/src/main/scala/ingestor.team.scala
So each ingestor has different logger name
=> Use new Logger[IO] for each ingestor

modules/api/src/main/scala/providers.scala, modules/api/src/main/smithy/_global.smithy, modules/api/src/main/smithy/search.smithy, modules/app/src/main/scala/service.search.scala, modules/client/src/main/scala/NoopSearchClient.scala, modules/client/src/main/scala/PlaySearchClient.scala, modules/e2e/src/test/scala/CompatSuite.scala
Save some unnecessary mappings
=> Use Id from core in api module

.gitignore, README.md, modules/ingestor/src/main/scala/cli.scala
For dev environments to seed/rebuild search indexes
```bash
sbt ingestor/runMain lila.search.ingestor.cli rebuild --drop
```
=> Add `index --all` for cli

modules/ingestor/src/main/scala/app.config.scala, modules/ingestor/src/main/scala/ingestor.forum.scala, modules/ingestor/src/main/scala/ingestor.game.scala, modules/ingestor/src/main/scala/ingestor.study.scala, modules/ingestor/src/main/scala/ingestor.team.scala, modules/ingestor/src/main/scala/package.scala
=> Use Instant directly at config loading

modules/app/src/main/scala/app.scala, modules/app/src/main/scala/http.logger.scala, modules/app/src/main/scala/http.middleware.scala, modules/app/src/main/scala/http.routes.scala
We keep the requirements minimal so We can add extra routes easier
=> Make httpRoutes returns http routes

project/Dependencies.scala
Allow customize prometheus exporter server shutdown timeout
=> Bump otel4s 0.11.1

project/Dependencies.scala, project/plugins.sbt
- smithy4s 0.18.26
- ciris 3.7.0
- otel4s 0.11.2
=> Bump dependencies

project/plugins.sbt
And remove scalafix-interfaces snapshot deps
=> Update scalafix 0.14.0

build.sbt, modules/app/src/main/scala/app.resources.scala, modules/app/src/main/scala/app.scala, modules/e2e/src/test/scala/IntegrationSuite.scala, modules/elastic/src/main/scala/ESClient.scala, modules/ingestor/src/main/scala/app.resources.scala, modules/ingestor/src/main/scala/app.scala, project/Dependencies.scala
https://github.com/Philippus/elastic4s/releases/tag/v9.0.0-RC1
=> Update elastic4s 9.0.0-RC1
